In [1]:
import numpy as np
from sklearn import preprocessing

In [2]:
# 导入包后，创建一些样本数据
data = np.array([[3,-1.5,2,-5.4],[0, 4, -0.3, 2.1],[1, 3.3, -1.9, -4.3]])

In [3]:
data

array([[ 3. , -1.5,  2. , -5.4],
       [ 0. ,  4. , -0.3,  2.1],
       [ 1. ,  3.3, -1.9, -4.3]])

In [4]:
# 均值移除
data_standardized = preprocessing.scale(data)
print '\nMean =',data_standardized.mean(axis=0)
print 'Std deviation =',data_standardized.std(axis=0)


Mean = [  5.55111512e-17  -1.11022302e-16  -7.40148683e-17  -7.40148683e-17]
Std deviation = [ 1.  1.  1.  1.]


### 范围缩放
### 数据预处理中每个特征的范围变化很大，因此，将特征的数值范围缩放到合理的范围很重要

In [5]:
data_scaler = preprocessing.MinMaxScaler(feature_range=(0,1))
data_scaled = data_scaler.fit_transform(data)
print '\nMin max scaled data=',data_scaled


Min max scaled data= [[ 1.          0.          1.          0.        ]
 [ 0.          1.          0.41025641  1.        ]
 [ 0.33333333  0.87272727  0.          0.14666667]]


### 归一化
### 归一化用于需要对特征向量的值进行调整时，保证每个特征向量的值都缩放到相同的数值范围。  
### 机器学习中最常用的归一化形式就是将特征向量调整为L1范数，使特征向量的数值之和为1

In [6]:
data_normalized = preprocessing.normalize(data,norm='l1')
print '\nL1 normalized data =',data_normalized


L1 normalized data = [[ 0.25210084 -0.12605042  0.16806723 -0.45378151]
 [ 0.          0.625      -0.046875    0.328125  ]
 [ 0.0952381   0.31428571 -0.18095238 -0.40952381]]


### 二值化
### 二值化用于将数值特征向量转换为布尔类型向量

In [7]:
data_binarized = preprocessing.Binarizer(threshold=0).transform(data)
print '\nBinarized data =',data_binarized


Binarized data = [[ 1.  0.  1.  0.]
 [ 0.  1.  0.  1.]
 [ 1.  1.  0.  0.]]
