In [1]:
from numpy import *

In [2]:
random.rand(4,4)

array([[ 0.8802819 ,  0.22940465,  0.39051804,  0.40337004],
       [ 0.80374439,  0.18239706,  0.46001876,  0.38203162],
       [ 0.76411916,  0.11145015,  0.95831771,  0.15979843],
       [ 0.88467827,  0.65445775,  0.12532175,  0.07308116]])

In [3]:
randMat = mat(random.rand(4,4))

In [4]:
randMat.I

matrix([[-1.54844951,  0.98040087, -0.13507966,  0.6014588 ],
        [ 1.40740127,  0.39538745, -0.25143675, -0.48796716],
        [ 0.62969572, -1.11215102, -0.53344098,  1.49448088],
        [ 0.10761485, -0.82523144,  2.30828029, -1.30111828]])

In [5]:
invRandMat = randMat.I

In [6]:
randMat*invRandMat

matrix([[  1.00000000e+00,   5.55111512e-17,  -1.11022302e-16,
           0.00000000e+00],
        [ -5.55111512e-17,   1.00000000e+00,  -5.55111512e-17,
          -2.77555756e-17],
        [ -1.66533454e-16,  -1.11022302e-16,   1.00000000e+00,
           3.33066907e-16],
        [ -2.08166817e-16,   1.38777878e-16,   0.00000000e+00,
           1.00000000e+00]])

In [7]:
myEye = randMat*invRandMat

In [8]:
myEye

matrix([[  1.00000000e+00,   5.55111512e-17,  -1.11022302e-16,
           0.00000000e+00],
        [ -5.55111512e-17,   1.00000000e+00,  -5.55111512e-17,
          -2.77555756e-17],
        [ -1.66533454e-16,  -1.11022302e-16,   1.00000000e+00,
           3.33066907e-16],
        [ -2.08166817e-16,   1.38777878e-16,   0.00000000e+00,
           1.00000000e+00]])

In [9]:
eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [10]:
mat(eye(4))

matrix([[ 1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  1.]])

In [11]:
myEye - mat(eye(4))

matrix([[  2.22044605e-16,   5.55111512e-17,  -1.11022302e-16,
           0.00000000e+00],
        [ -5.55111512e-17,   0.00000000e+00,  -5.55111512e-17,
          -2.77555756e-17],
        [ -1.66533454e-16,  -1.11022302e-16,   0.00000000e+00,
           3.33066907e-16],
        [ -2.08166817e-16,   1.38777878e-16,   0.00000000e+00,
           0.00000000e+00]])